---
- name: Install Laravel Dependencies
  hosts: localhost
  tasks:
    - name: Change to project directory
      command: cd /home/andu/file/Devops/laravel-backend-ci-cd

    - name: Install Composer dependencies
      command: composer install
      args:
        chdir: /home/andu/file/Devops/laravel-backend-ci-cd

    - name: Run Laravel migrations
      command: php artisan migrate
      args:
        chdir: /home/andu/file/Devops/laravel-backend-ci-cd
