all:
  hosts:
    localhost:
      ansible_connection: local
    webserver1:
      ansible_host: 192.168.1.10
    webserver2:
      ansible_host: 192.168.1.11
    dbserver1:
      ansible_host: 192.168.1.20
